name: IndicTrans2
channels:
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.11.26=h06a4308_0
  - joblib=1.4.2=py39h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libprotobuf=4.25.3=he621ea3_0
  - libsentencepiece=0.2.0=h70df78d_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - nltk=3.9.1=py39h06a4308_0
  - openssl=3.0.15=h5eee18b_0
  - python=3.9.19=h955ad1f_1
  - readline=8.2=h5eee18b_0
  - regex=2024.9.11=py39h5eee18b_0
  - sentencepiece-spm=0.2.0=h70df78d_2
  - setuptools=72.1.0=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tqdm=4.66.5=py39h2f386ee_0
  - wheel=0.44.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.11.7
      - aiosignal==1.3.1
      - alabaster==0.7.16
      - altair==5.4.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.8
      - anyio==4.4.0
      - appdirs==1.4.4
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==24.2.0
      - babel==2.16.0
      - bitarray==2.9.2
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.3.2
      - click==7.1.2
      - colorama==0.4.6
      - comet-ml==3.47.3
      - configobj==5.0.9
      - contourpy==1.3.0
      - ctranslate2==3.9.0
      - cycler==0.12.1
      - cython==3.0.11
      - dill==0.3.8
      - docopt==0.6.2
      - docutils==0.20.1
      - dulwich==0.22.6
      - entmax==1.3
      - everett==3.1.0
      - exceptiongroup==1.2.2
      - fairseq==0.12.2
      - fastapi==0.114.2
      - ffmpy==0.4.0
      - filelock==3.16.0
      - flatbuffers==24.3.25
      - fonttools==4.53.1
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - future==1.0.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - gradio==4.26.0
      - gradio-client==0.15.1
      - grpcio==1.66.1
      - h11==0.14.0
      - h5py==3.11.0
      - httpcore==1.0.5
      - httpx==0.27.2
      - huggingface-hub==0.24.7
      - hydra-core==1.0.7
      - idna==3.10
      - imagesize==1.4.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - indic-nlp-library==0.92
      - jinja2==3.1.4
      - jsonargparse==3.13.1
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - keras==3.5.0
      - kiwisolver==1.4.7
      - laser-encoders==0.0.2
      - laserembeddings==1.0.0
      - libclang==18.1.1
      - lightning-utilities==0.11.9
      - lxml==5.3.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - ml-dtypes==0.4.1
      - mock==5.1.0
      - morfessor==2.0.6
      - mosestokenizer==1.2.1
      - mpmath==1.3.0
      - multidict==6.1.0
      - namex==0.0.8
      - narwhals==1.8.1
      - networkx==3.2.1
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.0.6
      - openfile==0.0.7
      - opt-einsum==3.3.0
      - optree==0.12.1
      - orjson==3.10.7
      - packaging==24.1
      - pandas==2.2.2
      - pillow==10.4.0
      - pip==23.2.1
      - portalocker==2.10.1
      - promise==2.3
      - propcache==0.2.0
      - protobuf==4.25.5
      - psutil==6.1.0
      - pycparser==2.22
      - pydantic==2.9.1
      - pydantic-core==2.23.3
      - pydub==0.25.1
      - pygments==2.18.0
      - pyparsing==3.1.4
      - python-box==6.1.0
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.9
      - pytorch-lightning==2.4.0
      - pytz==2024.2
      - pyyaml==6.0.2
      - referencing==0.35.1
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rich==13.8.1
      - rpds-py==0.20.0
      - ruff==0.6.5
      - sacrebleu==2.3.1
      - sacremoses==0.0.35
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.13.1
      - semantic-version==2.10.0
      - sentence-transformers==3.3.1
      - sentencepiece==0.1.99
      - sentry-sdk==2.19.0
      - shellingham==1.5.4
      - simplejson==3.19.3
      - six==1.16.0
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - sphinx==7.4.7
      - sphinx-argparse==0.4.0
      - sphinx-rtd-theme==2.0.0
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - starlette==0.38.5
      - subword-nmt==0.3.8
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.18.0
      - tensorflow-addons==0.23.0
      - tensorflow-datasets==3.2.1
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-metadata==1.15.0
      - termcolor==2.4.0
      - tf-keras==2.18.0
      - tf2crf==0.1.33
      - threadpoolctl==3.5.0
      - tokenizers==0.20.3
      - tomli==2.0.1
      - tomlkit==0.12.0
      - toolwrapper==2.1.0
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchmetrics==0.10.3
      - torchvision==0.20.1+cu121
      - transformers==4.46.3
      - transliterate==1.10.2
      - triton==3.1.0
      - typeguard==2.13.3
      - typer==0.10.0
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - uctools==1.3.0
      - unbabel-comet==2.2.2
      - unicategories==0.1.2
      - urduhack==1.1.1
      - urllib3==2.2.3
      - uvicorn==0.30.6
      - websockets==11.0.3
      - werkzeug==3.0.4
      - wrapt==1.16.0
      - wurlitzer==3.1.1
      - yarl==1.18.0
      - zipp==3.20.2
prefix: /home/kpd/anaconda3/envs/itv2
