name: mBART50
channels:
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=2.1.0=pyhd8ed1ab_0
  - aiohappyeyeballs=2.4.0=py312h06a4308_0
  - aiohttp=3.10.5=py312h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - arrow-cpp=16.1.0=hc1eb8f0_0
  - attrs=23.1.0=py312h06a4308_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.10.55=h721c034_0
  - blas=1.0=mkl
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.3.7=py312ha883a20_0
  - brotli-python=1.0.9=py312h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.12.31=h06a4308_0
  - certifi=2024.12.14=py312h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - datasets=2.14.6=py_0
  - expat=2.6.3=h6a678d5_0
  - filelock=3.13.1=py312h06a4308_0
  - frozenlist=1.4.0=py312h5eee18b_0
  - gflags=2.2.2=h6a678d5_1
  - glog=0.5.0=h6a678d5_1
  - grpcio=1.62.2=py312h6a678d5_0
  - huggingface_hub=0.25.1=py_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py312h06a4308_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libcurl=8.9.1=h251f7ec_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgomp=14.2.0=h77fa898_1
  - libgrpc=1.62.2=h2d74bed_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libprotobuf=4.25.3=he621ea3_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libthrift=0.15.0=h1795dd8_2
  - libuuid=1.41.5=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown=3.6=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_1
  - mkl_fft=1.3.10=py312h5eee18b_0
  - mkl_random=1.2.7=py312h526ad5a_0
  - multidict=6.0.4=py312h5eee18b_0
  - multiprocess=0.70.15=py312h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - numexpr=2.8.7=py312hf827012_0
  - numpy=1.26.4=py312hc5e2394_0
  - numpy-base=1.26.4=py312h0da6c21_0
  - openssl=3.4.0=hb9d3cd8_0
  - orc=2.0.1=h2d29ad5_0
  - packaging=24.1=py312h06a4308_0
  - pandas=2.2.2=py312h526ad5a_0
  - protobuf=4.25.3=py312h12ddb61_0
  - pyarrow=16.1.0=py312h526ad5a_0
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.5=h5148396_1
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-xxhash=2.0.2=py312h5eee18b_1
  - pytz=2024.1=py312h06a4308_0
  - pyyaml=6.0.1=py312h5eee18b_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py312h06a4308_0
  - s2n=1.3.27=hdbd6064_0
  - setuptools=75.1.0=py312h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tensorboard=2.18.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py312h52d8a92_1
  - tk=8.6.14=h39e8969_0
  - tqdm=4.66.5=py312he106c6f_0
  - typing-extensions=4.11.0=py312h06a4308_0
  - typing_extensions=4.11.0=py312h06a4308_0
  - tzdata=2024a=h04d1e81_0
  - urllib3=2.2.2=py312h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - werkzeug=3.1.3=pyhff2d567_0
  - wheel=0.44.0=py312h06a4308_0
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.11.0=py312h5eee18b_0
  - zipp=3.21.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - accelerate==1.7.0
      - colorama==0.4.6
      - dill==0.3.7
      - entmax==1.3
      - evaluate==0.4.3
      - fsspec==2023.10.0
      - hf-xet==1.1.2
      - huggingface-hub==0.32.3
      - jinja2==3.1.4
      - jsonargparse==3.13.1
      - lightning-utilities==0.11.9
      - lxml==5.3.0
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.3
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - pillow==10.4.0
      - pip==25.0
      - portalocker==2.10.1
      - psutil==6.0.0
      - pyter3==0.3
      - pytorch-lightning==2.5.0.post0
      - regex==2024.9.11
      - sacrebleu==2.4.3
      - safetensors==0.4.5
      - scipy==1.15.1
      - sentencepiece==0.2.0
      - sympy==1.13.3
      - tabulate==0.9.0
      - tokenizers==0.21.1
      - torch==2.7.1
      - torchaudio==2.4.1
      - torchmetrics==0.10.3
      - torchvision==0.22.1+cu126
      - transformers==4.53.0.dev0
      - triton==3.3.1
      - unbabel-comet==2.2.4
prefix: /home/kpd/anaconda3/envs/hgftransformer
