name: NLLB-200
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.1.31=hbcca054_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgomp=14.2.0=h77fa898_1
  - liblzma=5.6.4=hb9d3cd8_0
  - liblzma-devel=5.6.4=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.48.0=hee588c1_1
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.4.0=h7b32b05_1
  - pip=25.0=pyh8b19718_0
  - python=3.12.5=h2ad013b_0_cpython
  - readline=8.2=h8228510_1
  - setuptools=75.8.0=pyhff2d567_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.45.1=pyhd8ed1ab_1
  - xz=5.6.4=hbcc6ac9_0
  - xz-gpl-tools=5.6.4=hbcc6ac9_0
  - xz-tools=5.6.4=hb9d3cd8_0
  - pip:
      - accelerate==1.3.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.12
      - aiosignal==1.3.2
      - attrs==25.1.0
      - bitsandbytes==0.45.2
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - colorama==0.4.6
      - datasets==3.2.0
      - dill==0.3.8
      - evaluate==0.4.3
      - filelock==3.17.0
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - huggingface-hub==0.28.1
      - idna==3.10
      - jinja2==3.1.4
      - lxml==5.3.0
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - networkx==3.3
      - numpy==2.2.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.1.105
      - nvidia-nvtx-cu12==12.1.105
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.0.0
      - portalocker==3.1.1
      - propcache==0.2.1
      - protobuf==5.29.3
      - psutil==6.1.1
      - pyarrow==19.0.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - sacrebleu==2.5.1
      - safetensors==0.5.2
      - six==1.17.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboardx==2.6.2.2
      - tokenizers==0.20.3
      - torch==2.4.1+cu121
      - torchaudio==2.4.1+cu121
      - torchvision==0.19.1+cu121
      - tqdm==4.67.1
      - transformers==4.45.1
      - triton==3.0.0
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.3.0
      - xxhash==3.5.0
      - yarl==1.18.3
prefix: /home/kpd/anaconda3/envs/nllb_env2
