name: opus_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h993c535_1
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.3.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.11
      - aiosignal==1.3.2
      - async-timeout==5.0.1
      - attrs==25.3.0
      - automat==25.4.16
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - colorama==0.4.6
      - comet==3.1.0
      - constantly==23.10.4
      - datasets==3.6.0
      - dill==0.3.8
      - filelock==3.18.0
      - frozenlist==1.6.2
      - fsspec==2025.3.0
      - grpcio==1.72.1
      - hf-xet==1.1.3
      - huggingface-hub==0.32.4
      - hyperlink==21.0.0
      - idna==3.10
      - incremental==24.7.2
      - jinja2==3.1.6
      - lxml==5.4.0
      - markdown==3.8
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - multidict==6.4.4
      - multiprocess==0.70.16
      - networkx==3.4.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - packaging==25.0
      - pandas==2.3.0
      - portalocker==3.1.1
      - propcache==0.3.1
      - protobuf==6.31.1
      - pyarrow==20.0.0
      - pyter3==0.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - sacrebleu==2.5.1
      - safetensors==0.5.3
      - sentencepiece==0.2.0
      - six==1.17.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tokenizers==0.21.1
      - tomli==2.2.1
      - torch==2.7.1
      - tqdm==4.67.1
      - transformers==4.52.4
      - triton==3.3.1
      - twisted==25.5.0
      - typing-extensions==4.14.0
      - tzdata==2025.2
      - urllib3==2.4.0
      - werkzeug==3.1.3
      - xxhash==3.5.0
      - yarl==1.20.0
      - zope-interface==7.2
prefix: /home/kpd/anaconda3/envs/opus_env
